### ISSUE TITLE
tools / ctc-hulks  compiling error

### ISSUE THREAD

**Issue by Heodel** [HULKs/HULKsCodeRelease#1]
I compiled three times according to the instructions in Ubuntu 18.04 Ubuntu 17 Ubuntu 16.04

It's all compiling / tools / ctc-hulks and it's the same error

```
Root@star:/HULKs CodeRelease-master/tools/ctc-hulks#. /3-build-libs

3-build-libs: Line 11: / HULKs Code Release-master/tools/ctc-hulks/x-tools/i686-nao-linux-gnu/bin/i686-nao-linux-gnu-gcc: No file or directory

. / 3-build-libs: Line 17: cd: bzip2-1.0.6: No file or directory

Make: *** No rule to make target'libbz2.a'. Stop it.

Install: Cannot get the file status of'libbz2.a'(stat): No file or directory

Install: Cannot get the file status of'bzlib.h'(stat): No file or directory

Make: *** No rule to make target'clean'. Stop it.

Make: Makefile-libbz2_so: No file or directory

Make: *** No rule to make target'Makefile-libbz2_so'. Stop it.

Install: Cannot get the file status of'libbz2.so.1.0.6'(stat): No file or directory

Finished bzip2. Continue? [y/n] y

. / 3-build-libs: Line 29: cd: zlib-1.2.11: No file or directory

. / 3-build-libs: Line 30:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished zlib. Continue? [y/n] y

. / 3-build-libs: Line 37: cd: libpng-1.6.34: No file or directory

. / 3-build-libs: Line 38:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished libpng. Continue? [y/n] y

. / 3-build-libs: Line 48: cd: libjpeg-turbo-1.5.3: No file or directory

Autoreconf:'configure.ac'or'configure.in' is required

. / 3-build-libs: Line 50:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished libjpeg. Continue? [y/n] y

. / 3-build-libs: Line 60: cd: boost_1_66_0/tools/build: No file or directory

Can't find file to patch at input line 5

Perhaps you used the wrong-p or -- strip option?

The text leading up to this was:

------------------------------------------------------------------------------------------------------------------------------

| diff -- git a/src/build/ac.jam b/src/build/ac.jam

| index c6e36c6..C01dc59 100644

| - a/src/build/ac.jam

|+++ b/src/build/ac.jam

------------------------------------------------------------------------------------------------------------------------------

File to patch:

Skip this patch? [y]y

Skipping patch.

2 out of 2 hunks ignored

. / 3-build-libs: Line 62:. / bootstrap. sh: No file or directory

. / 3-build-libs: Line 63:. / b2: No file or directory

. / 3-build-libs: Line 67: / HULKs Code Release-master/tools/ctc-hulks/libs/boost-build/bin/b2: No file or directory

Finished boost. Continue? [y/n] y

CMake Error: The source directory "/ flann-1.9.1" does not exist.

Specify -- help for usage, or press the help button on the CMake GUI.

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished flann. Continue? [y/n] y

. / 3-build-libs: Line 88: cd: eigen-3.3.4: No file or directory

Can't find file to patch at input line 3

Perhaps you used the wrong-p or -- strip option?

The text leading up to this was:

------------------------------------------------------------------------------------------------------------------------------

| - a/unsupported/test/CMakeLists.txt Tue Feb 21 14:36:34 2017+0100

|+++ b/unsupported/test/CMakeLists.txt Wed Feb 2202:55:35 2017+0100

------------------------------------------------------------------------------------------------------------------------------

File to patch:

Skip this patch? [y]y

Skipping patch.

2 out of 2 hunks ignored

CMake Error: The source directory "/ eigen-3.3.4" does not exist.

Specify -- help for usage, or press the help button on the CMake GUI.

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished Eigen. Continue? [y/n] y

. / 3-build-libs: Line 106: cd: alsa-lib-1.1.5: No file or directory

. / 3-build-libs: Line 107:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished alsa. Continue? [y/n] y

CMake Error: The source directory "/ portaudio-v190600_20161030" does not exist.

Specify -- help for usage, or press the help button on the CMake GUI.

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished portaudio. Continue? [y/n] y

. / 3-build-libs: Line 130: cd: libsndfile-1.0.28: No file or directory

. / 3-build-libs: Line 131:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished libsndfile. Continue? [y/n]y

. / 3-build-libs: Line 140: cd: fftw-3.3.7: No file or directory

. / 3-build-libs: Line 141:. / configure: No file or directory

Make: *** No target was specified and makefile could not be found. Stop it.

Make: *** No rule to make target'install'. Stop it.

Finished fftw. Continue? [y/n] y
```

Can you help me?....If you can I would be very appreciate!

**Comment by rkost** [comment]
We are missing some log output here. Looks like the previous script (2) did not download all dependencies. Can you execute that one again and paste the log? If it worked there should be a new sub-folder in the `x-tools` folder.

**Comment by Heodel** [comment]
Thank you very much! I compiled it successfully!
I analyzed the log found is my network problem.

But when I compile the SimRobot , I encountered an error in the cpp file , which is in the Motion section.
I compiled it four times and used the following instructions:

nao /scripts/compile -t simrobot -b <BUILD_TYPE>

The type I used as Develop Debug Release and RelWithDebInfo

This command is in section 2.4.3 of the manual book.

Below is my error log:


Heodel@star:~/HULKsCodeRelease-master$ ./scripts/compile -t simrobot -b Debug
-- Compiling for target simrobot with build type Debug.

[ 1%] Automatic moc for target tuhhSimRobot
[ 1%] Built target tuhhSimRobot_automoc
[ 13%] Built target Vision
[ 32%] Built target Motion
Scanning dependencies of target Brain
[ 33%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o
[ 34%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/Obstacles/TeamObstacleFilter.cpp.o
[ 35%] Building CXX object src/brain/CMakeFiles/Brain.dir/Knowledge/Obstacles/ObstacleFilter.cpp.o
[ 36%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/CollisionDetection/CollisionDetector.cpp.o
[ 36%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/FootCollisionDetector/FootCollisionDetector.cpp.o
[ 37%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/HeadDamageProvider/HeadDamageProvider.cpp.o
[ 37%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/MotionPlanning/MotionPlanner.cpp.o

/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp: In member function 'std::tuple<bool, long unsigned int, float> LandmarkFilter::findCenterLineOrientation(const std::vector<LineInfo >&, const LandmarkFilter::PointCluster2D&)':
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:464:45: error: converting to 'std::tuple<bool, long unsigned int, float>' from initializer list would use explicit Constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {bool, long unsigned int&, float&}; <template-parameter-2-2> = void; _Elements = {bool, long unsigned int, float}]'
     Return {true, longestLineId, orientation};
                                             ^
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:466:25: error: converting to 'std::tuple<bool, long unsigned int, float>' from initializer list would use explicit Constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {bool, int, float}; <template-parameter-2-2> = void ; _Elements = {bool, long unsigned int, float}]'
   Return {false, -1, 0.f};
                         ^
[ 38%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/WhistleDetection/WhistleDetection.cpp.o

/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp: In member function ‘std::tuple<bool, float> LandmarkFilter::findIntersectionOrientation(const LandmarkModel::Intersection&)’:
/home/heodel/HULKsCodeRelease-master/src/brain/Knowledge/LandmarkFilter/LandmarkFilter.cpp:796:38: error: converting to 'std::tuple<bool, float>' from initializer list would use explicit constructor 'constexpr std ::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = bool&; _U2 = float&; <template-parameter-2-3> = void; _T1 = bool; _T2 = float]'
   Return {hasOrientation, orientation};
                                      ^
[ 39%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/ReplayRecorder/ReplayRecorder.cpp.o
[ 39%] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/OdometryOffsetProvider/OdometryOffsetProvider.cpp.o
[ 40% ] Building CXX object src/brain/CMakeFiles/Brain.dir/Modules/TeamPlayersAugmenter/TeamPlayersAugmenter.cpp.o
[ 41%] Building CXX object src/brain/CMakeFiles/Brain.dir/SPLNetwork/HULKsMessage.cpp.o
Src/brain/CMakeFiles/Brain.dir/build.make:614: recipe for target 'src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o' failed
Make[2]: *** [src/brain/CMakeFiles/Brain.dir/Knowledge/LandmarkFilter/LandmarkFilter.cpp.o] Error 1
Make[2]: *** Waiting for unfinished tasks....
CMakeFiles/Makefile2:215: recipe for target 'src/brain/CMakeFiles/Brain.dir/all' failed
Make[1]: *** [src/brain/CMakeFiles/Brain.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
Make: *** [all] Error 2
-- Compilation failed!


If you can help me I would be appreciate!

**Comment by rkost** [comment]
Hey @Heodel

as your new problem has nothing to do with the title of this issue, I created a new one (#2) and will help you there.

I will close this issue for now, as you wrote that you were able to compile the toolchain successfully.
