### ISSUE TITLE
Can not changePlayerNumber

### ISSUE THREAD

**Issue by TeaBambooNGU** [HULKs/HULKsCodeRelease#4]
I meet an error when I run  `./scripts/changePlayerNumber`

this is my error message:

> heodel@star:~/HULKsCodeRelease-master$ ./scripts/changePlayerNumber 12:4
> 
> Traceback (most recent call last):
>   File "./scripts/changePlayerNumber", line 85, in <module>
>     change_player_numbers(naonumber_playernumber_dict)
>   File "./scripts/changePlayerNumber", line 71, in change_player_numbers
>     with open(brain_json_path, 'r') as file:
> IOError: [Errno 2] No such file or directory: '/home/heodel/HULKsCodeRelease-master/scripts/../home/configuration/location/default/head/tuhhnao12/Brain.json' 

I don't know why not have these files like `head/tuhhnao12/Brain.json` in my computer.

**Comment by rkost** [comment]
We deleted our robot specific config from the repository as it needs to be changed for every robot anyway. All robots need to have a `Brain.json` which contains at least their player number. A typical robot-specific brain config looks like this:

```
{
    "general.playerNumber": 2
}
```

The script simply searches for the config directory of the given robot (in your case it is robot 12 which translates to the directory `home/configuration/location/default/head/tuhhnao12`, opens the given brain config file and changes the player number to e.g. 4.

So for your problem you need to create the brain config file in the given directory for every robot you have.

**Comment by rkost** [comment]
Did this solve your problem?

**Comment by TeaBambooNGU** [comment]
yep, sorry, I forget to close this issue.

**Comment by rkost** [comment]
Cool. We will include this hint in our next TRR.
