### ISSUE TITLE
Incomplete configuration manual

### ISSUE THREAD

**Issue by HiddeLekanne** [HULKs/HULKsCodeRelease#9]
You need to fill in your teamnumber into multiple files in order for (at least) robotSim to work, one of which isn't mentioned in the teamreport (checked by Ctr+F). 

The file in question:
HULKsCodeRelease/home/configuration/location/default/head/default/Brain.json
Content:
```
{
    "general.teamNumber": YOUR_TEAM_NUMBER_HERE,
    "general.port": 100YOUR_TEAM_NUMBER_HERE,
    "behavior.playerRole": "player",
    "behavior.initialPoses": [ -3, -2, -1, -1, -2, -3 ]
}
```

Fixing it was trivial, finding it was not.

**Comment by rkost** [comment]
Sorry about that. I will fix that in our TRR

**Comment by rkost** [comment]
Fixed, https://hulks.de/_files/TRR_2019.pdf

Thanks for reporting!
